// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: PublicTransportationService.proto

package com.example.PublicTransportationService;

/**
 * Protobuf type {@code PublicTransportationService.DispatchVehicleResponse}
 */
public  final class DispatchVehicleResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:PublicTransportationService.DispatchVehicleResponse)
    DispatchVehicleResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use DispatchVehicleResponse.newBuilder() to construct.
  private DispatchVehicleResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private DispatchVehicleResponse() {
    vehicleId_ = "";
    estimatedArrivalTime_ = "";
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private DispatchVehicleResponse(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            vehicleId_ = s;
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            estimatedArrivalTime_ = s;
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.example.PublicTransportationService.TransitProto.internal_static_PublicTransportationService_DispatchVehicleResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.example.PublicTransportationService.TransitProto.internal_static_PublicTransportationService_DispatchVehicleResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.example.PublicTransportationService.DispatchVehicleResponse.class, com.example.PublicTransportationService.DispatchVehicleResponse.Builder.class);
  }

  public static final int VEHICLE_ID_FIELD_NUMBER = 1;
  private volatile java.lang.Object vehicleId_;
  /**
   * <code>string vehicle_id = 1;</code>
   */
  public java.lang.String getVehicleId() {
    java.lang.Object ref = vehicleId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      vehicleId_ = s;
      return s;
    }
  }
  /**
   * <code>string vehicle_id = 1;</code>
   */
  public com.google.protobuf.ByteString
      getVehicleIdBytes() {
    java.lang.Object ref = vehicleId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      vehicleId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ESTIMATED_ARRIVAL_TIME_FIELD_NUMBER = 2;
  private volatile java.lang.Object estimatedArrivalTime_;
  /**
   * <code>string estimated_arrival_time = 2;</code>
   */
  public java.lang.String getEstimatedArrivalTime() {
    java.lang.Object ref = estimatedArrivalTime_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      estimatedArrivalTime_ = s;
      return s;
    }
  }
  /**
   * <code>string estimated_arrival_time = 2;</code>
   */
  public com.google.protobuf.ByteString
      getEstimatedArrivalTimeBytes() {
    java.lang.Object ref = estimatedArrivalTime_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      estimatedArrivalTime_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getVehicleIdBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, vehicleId_);
    }
    if (!getEstimatedArrivalTimeBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, estimatedArrivalTime_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getVehicleIdBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, vehicleId_);
    }
    if (!getEstimatedArrivalTimeBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, estimatedArrivalTime_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.example.PublicTransportationService.DispatchVehicleResponse)) {
      return super.equals(obj);
    }
    com.example.PublicTransportationService.DispatchVehicleResponse other = (com.example.PublicTransportationService.DispatchVehicleResponse) obj;

    boolean result = true;
    result = result && getVehicleId()
        .equals(other.getVehicleId());
    result = result && getEstimatedArrivalTime()
        .equals(other.getEstimatedArrivalTime());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + VEHICLE_ID_FIELD_NUMBER;
    hash = (53 * hash) + getVehicleId().hashCode();
    hash = (37 * hash) + ESTIMATED_ARRIVAL_TIME_FIELD_NUMBER;
    hash = (53 * hash) + getEstimatedArrivalTime().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.example.PublicTransportationService.DispatchVehicleResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.example.PublicTransportationService.DispatchVehicleResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.example.PublicTransportationService.DispatchVehicleResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.example.PublicTransportationService.DispatchVehicleResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.example.PublicTransportationService.DispatchVehicleResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.example.PublicTransportationService.DispatchVehicleResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.example.PublicTransportationService.DispatchVehicleResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.example.PublicTransportationService.DispatchVehicleResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.example.PublicTransportationService.DispatchVehicleResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.example.PublicTransportationService.DispatchVehicleResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.example.PublicTransportationService.DispatchVehicleResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.example.PublicTransportationService.DispatchVehicleResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.example.PublicTransportationService.DispatchVehicleResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code PublicTransportationService.DispatchVehicleResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:PublicTransportationService.DispatchVehicleResponse)
      com.example.PublicTransportationService.DispatchVehicleResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.example.PublicTransportationService.TransitProto.internal_static_PublicTransportationService_DispatchVehicleResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.example.PublicTransportationService.TransitProto.internal_static_PublicTransportationService_DispatchVehicleResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.example.PublicTransportationService.DispatchVehicleResponse.class, com.example.PublicTransportationService.DispatchVehicleResponse.Builder.class);
    }

    // Construct using com.example.PublicTransportationService.DispatchVehicleResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      vehicleId_ = "";

      estimatedArrivalTime_ = "";

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.example.PublicTransportationService.TransitProto.internal_static_PublicTransportationService_DispatchVehicleResponse_descriptor;
    }

    @java.lang.Override
    public com.example.PublicTransportationService.DispatchVehicleResponse getDefaultInstanceForType() {
      return com.example.PublicTransportationService.DispatchVehicleResponse.getDefaultInstance();
    }

    @java.lang.Override
    public com.example.PublicTransportationService.DispatchVehicleResponse build() {
      com.example.PublicTransportationService.DispatchVehicleResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.example.PublicTransportationService.DispatchVehicleResponse buildPartial() {
      com.example.PublicTransportationService.DispatchVehicleResponse result = new com.example.PublicTransportationService.DispatchVehicleResponse(this);
      result.vehicleId_ = vehicleId_;
      result.estimatedArrivalTime_ = estimatedArrivalTime_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.example.PublicTransportationService.DispatchVehicleResponse) {
        return mergeFrom((com.example.PublicTransportationService.DispatchVehicleResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.example.PublicTransportationService.DispatchVehicleResponse other) {
      if (other == com.example.PublicTransportationService.DispatchVehicleResponse.getDefaultInstance()) return this;
      if (!other.getVehicleId().isEmpty()) {
        vehicleId_ = other.vehicleId_;
        onChanged();
      }
      if (!other.getEstimatedArrivalTime().isEmpty()) {
        estimatedArrivalTime_ = other.estimatedArrivalTime_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.example.PublicTransportationService.DispatchVehicleResponse parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.example.PublicTransportationService.DispatchVehicleResponse) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object vehicleId_ = "";
    /**
     * <code>string vehicle_id = 1;</code>
     */
    public java.lang.String getVehicleId() {
      java.lang.Object ref = vehicleId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        vehicleId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string vehicle_id = 1;</code>
     */
    public com.google.protobuf.ByteString
        getVehicleIdBytes() {
      java.lang.Object ref = vehicleId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        vehicleId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string vehicle_id = 1;</code>
     */
    public Builder setVehicleId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      vehicleId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string vehicle_id = 1;</code>
     */
    public Builder clearVehicleId() {
      
      vehicleId_ = getDefaultInstance().getVehicleId();
      onChanged();
      return this;
    }
    /**
     * <code>string vehicle_id = 1;</code>
     */
    public Builder setVehicleIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      vehicleId_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object estimatedArrivalTime_ = "";
    /**
     * <code>string estimated_arrival_time = 2;</code>
     */
    public java.lang.String getEstimatedArrivalTime() {
      java.lang.Object ref = estimatedArrivalTime_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        estimatedArrivalTime_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string estimated_arrival_time = 2;</code>
     */
    public com.google.protobuf.ByteString
        getEstimatedArrivalTimeBytes() {
      java.lang.Object ref = estimatedArrivalTime_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        estimatedArrivalTime_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string estimated_arrival_time = 2;</code>
     */
    public Builder setEstimatedArrivalTime(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      estimatedArrivalTime_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string estimated_arrival_time = 2;</code>
     */
    public Builder clearEstimatedArrivalTime() {
      
      estimatedArrivalTime_ = getDefaultInstance().getEstimatedArrivalTime();
      onChanged();
      return this;
    }
    /**
     * <code>string estimated_arrival_time = 2;</code>
     */
    public Builder setEstimatedArrivalTimeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      estimatedArrivalTime_ = value;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:PublicTransportationService.DispatchVehicleResponse)
  }

  // @@protoc_insertion_point(class_scope:PublicTransportationService.DispatchVehicleResponse)
  private static final com.example.PublicTransportationService.DispatchVehicleResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.example.PublicTransportationService.DispatchVehicleResponse();
  }

  public static com.example.PublicTransportationService.DispatchVehicleResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<DispatchVehicleResponse>
      PARSER = new com.google.protobuf.AbstractParser<DispatchVehicleResponse>() {
    @java.lang.Override
    public DispatchVehicleResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new DispatchVehicleResponse(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<DispatchVehicleResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<DispatchVehicleResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.example.PublicTransportationService.DispatchVehicleResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

