// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: PublicTransportationService.proto

package com.example.PublicTransportationService;

public interface DispatchVehicleRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:PublicTransportationService.DispatchVehicleRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string vehicle_type = 1;</code>
   */
  java.lang.String getVehicleType();
  /**
   * <code>string vehicle_type = 1;</code>
   */
  com.google.protobuf.ByteString
      getVehicleTypeBytes();

  /**
   * <code>string destination_location = 2;</code>
   */
  java.lang.String getDestinationLocation();
  /**
   * <code>string destination_location = 2;</code>
   */
  com.google.protobuf.ByteString
      getDestinationLocationBytes();
}
