// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: PublicTransportationService.proto

package com.example.PublicTransportationService;

public interface DispatchVehicleResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:PublicTransportationService.DispatchVehicleResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string vehicle_id = 1;</code>
   */
  java.lang.String getVehicleId();
  /**
   * <code>string vehicle_id = 1;</code>
   */
  com.google.protobuf.ByteString
      getVehicleIdBytes();

  /**
   * <code>string estimated_arrival_time = 2;</code>
   */
  java.lang.String getEstimatedArrivalTime();
  /**
   * <code>string estimated_arrival_time = 2;</code>
   */
  com.google.protobuf.ByteString
      getEstimatedArrivalTimeBytes();
}
