// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: PublicTransportationService.proto

package com.example.PublicTransportationService;

/**
 * Protobuf type {@code PublicTransportationService.StopArrivalTimeResponse}
 */
public  final class StopArrivalTimeResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:PublicTransportationService.StopArrivalTimeResponse)
    StopArrivalTimeResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use StopArrivalTimeResponse.newBuilder() to construct.
  private StopArrivalTimeResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private StopArrivalTimeResponse() {
    stopId_ = "";
    currentLocation_ = "";
    estimatedMinutes_ = 0;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private StopArrivalTimeResponse(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            stopId_ = s;
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            currentLocation_ = s;
            break;
          }
          case 24: {

            estimatedMinutes_ = input.readInt32();
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.example.PublicTransportationService.TransitProto.internal_static_PublicTransportationService_StopArrivalTimeResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.example.PublicTransportationService.TransitProto.internal_static_PublicTransportationService_StopArrivalTimeResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.example.PublicTransportationService.StopArrivalTimeResponse.class, com.example.PublicTransportationService.StopArrivalTimeResponse.Builder.class);
  }

  public static final int STOP_ID_FIELD_NUMBER = 1;
  private volatile java.lang.Object stopId_;
  /**
   * <code>string stop_id = 1;</code>
   */
  public java.lang.String getStopId() {
    java.lang.Object ref = stopId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      stopId_ = s;
      return s;
    }
  }
  /**
   * <code>string stop_id = 1;</code>
   */
  public com.google.protobuf.ByteString
      getStopIdBytes() {
    java.lang.Object ref = stopId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      stopId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int CURRENT_LOCATION_FIELD_NUMBER = 2;
  private volatile java.lang.Object currentLocation_;
  /**
   * <code>string current_location = 2;</code>
   */
  public java.lang.String getCurrentLocation() {
    java.lang.Object ref = currentLocation_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      currentLocation_ = s;
      return s;
    }
  }
  /**
   * <code>string current_location = 2;</code>
   */
  public com.google.protobuf.ByteString
      getCurrentLocationBytes() {
    java.lang.Object ref = currentLocation_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      currentLocation_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ESTIMATED_MINUTES_FIELD_NUMBER = 3;
  private int estimatedMinutes_;
  /**
   * <code>int32 estimated_minutes = 3;</code>
   */
  public int getEstimatedMinutes() {
    return estimatedMinutes_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getStopIdBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, stopId_);
    }
    if (!getCurrentLocationBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, currentLocation_);
    }
    if (estimatedMinutes_ != 0) {
      output.writeInt32(3, estimatedMinutes_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getStopIdBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, stopId_);
    }
    if (!getCurrentLocationBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, currentLocation_);
    }
    if (estimatedMinutes_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(3, estimatedMinutes_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.example.PublicTransportationService.StopArrivalTimeResponse)) {
      return super.equals(obj);
    }
    com.example.PublicTransportationService.StopArrivalTimeResponse other = (com.example.PublicTransportationService.StopArrivalTimeResponse) obj;

    boolean result = true;
    result = result && getStopId()
        .equals(other.getStopId());
    result = result && getCurrentLocation()
        .equals(other.getCurrentLocation());
    result = result && (getEstimatedMinutes()
        == other.getEstimatedMinutes());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + STOP_ID_FIELD_NUMBER;
    hash = (53 * hash) + getStopId().hashCode();
    hash = (37 * hash) + CURRENT_LOCATION_FIELD_NUMBER;
    hash = (53 * hash) + getCurrentLocation().hashCode();
    hash = (37 * hash) + ESTIMATED_MINUTES_FIELD_NUMBER;
    hash = (53 * hash) + getEstimatedMinutes();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.example.PublicTransportationService.StopArrivalTimeResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.example.PublicTransportationService.StopArrivalTimeResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.example.PublicTransportationService.StopArrivalTimeResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.example.PublicTransportationService.StopArrivalTimeResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.example.PublicTransportationService.StopArrivalTimeResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.example.PublicTransportationService.StopArrivalTimeResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.example.PublicTransportationService.StopArrivalTimeResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.example.PublicTransportationService.StopArrivalTimeResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.example.PublicTransportationService.StopArrivalTimeResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.example.PublicTransportationService.StopArrivalTimeResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.example.PublicTransportationService.StopArrivalTimeResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.example.PublicTransportationService.StopArrivalTimeResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.example.PublicTransportationService.StopArrivalTimeResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code PublicTransportationService.StopArrivalTimeResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:PublicTransportationService.StopArrivalTimeResponse)
      com.example.PublicTransportationService.StopArrivalTimeResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.example.PublicTransportationService.TransitProto.internal_static_PublicTransportationService_StopArrivalTimeResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.example.PublicTransportationService.TransitProto.internal_static_PublicTransportationService_StopArrivalTimeResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.example.PublicTransportationService.StopArrivalTimeResponse.class, com.example.PublicTransportationService.StopArrivalTimeResponse.Builder.class);
    }

    // Construct using com.example.PublicTransportationService.StopArrivalTimeResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      stopId_ = "";

      currentLocation_ = "";

      estimatedMinutes_ = 0;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.example.PublicTransportationService.TransitProto.internal_static_PublicTransportationService_StopArrivalTimeResponse_descriptor;
    }

    @java.lang.Override
    public com.example.PublicTransportationService.StopArrivalTimeResponse getDefaultInstanceForType() {
      return com.example.PublicTransportationService.StopArrivalTimeResponse.getDefaultInstance();
    }

    @java.lang.Override
    public com.example.PublicTransportationService.StopArrivalTimeResponse build() {
      com.example.PublicTransportationService.StopArrivalTimeResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.example.PublicTransportationService.StopArrivalTimeResponse buildPartial() {
      com.example.PublicTransportationService.StopArrivalTimeResponse result = new com.example.PublicTransportationService.StopArrivalTimeResponse(this);
      result.stopId_ = stopId_;
      result.currentLocation_ = currentLocation_;
      result.estimatedMinutes_ = estimatedMinutes_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.example.PublicTransportationService.StopArrivalTimeResponse) {
        return mergeFrom((com.example.PublicTransportationService.StopArrivalTimeResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.example.PublicTransportationService.StopArrivalTimeResponse other) {
      if (other == com.example.PublicTransportationService.StopArrivalTimeResponse.getDefaultInstance()) return this;
      if (!other.getStopId().isEmpty()) {
        stopId_ = other.stopId_;
        onChanged();
      }
      if (!other.getCurrentLocation().isEmpty()) {
        currentLocation_ = other.currentLocation_;
        onChanged();
      }
      if (other.getEstimatedMinutes() != 0) {
        setEstimatedMinutes(other.getEstimatedMinutes());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.example.PublicTransportationService.StopArrivalTimeResponse parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.example.PublicTransportationService.StopArrivalTimeResponse) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object stopId_ = "";
    /**
     * <code>string stop_id = 1;</code>
     */
    public java.lang.String getStopId() {
      java.lang.Object ref = stopId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        stopId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string stop_id = 1;</code>
     */
    public com.google.protobuf.ByteString
        getStopIdBytes() {
      java.lang.Object ref = stopId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        stopId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string stop_id = 1;</code>
     */
    public Builder setStopId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      stopId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string stop_id = 1;</code>
     */
    public Builder clearStopId() {
      
      stopId_ = getDefaultInstance().getStopId();
      onChanged();
      return this;
    }
    /**
     * <code>string stop_id = 1;</code>
     */
    public Builder setStopIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      stopId_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object currentLocation_ = "";
    /**
     * <code>string current_location = 2;</code>
     */
    public java.lang.String getCurrentLocation() {
      java.lang.Object ref = currentLocation_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        currentLocation_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string current_location = 2;</code>
     */
    public com.google.protobuf.ByteString
        getCurrentLocationBytes() {
      java.lang.Object ref = currentLocation_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        currentLocation_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string current_location = 2;</code>
     */
    public Builder setCurrentLocation(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      currentLocation_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string current_location = 2;</code>
     */
    public Builder clearCurrentLocation() {
      
      currentLocation_ = getDefaultInstance().getCurrentLocation();
      onChanged();
      return this;
    }
    /**
     * <code>string current_location = 2;</code>
     */
    public Builder setCurrentLocationBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      currentLocation_ = value;
      onChanged();
      return this;
    }

    private int estimatedMinutes_ ;
    /**
     * <code>int32 estimated_minutes = 3;</code>
     */
    public int getEstimatedMinutes() {
      return estimatedMinutes_;
    }
    /**
     * <code>int32 estimated_minutes = 3;</code>
     */
    public Builder setEstimatedMinutes(int value) {
      
      estimatedMinutes_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 estimated_minutes = 3;</code>
     */
    public Builder clearEstimatedMinutes() {
      
      estimatedMinutes_ = 0;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:PublicTransportationService.StopArrivalTimeResponse)
  }

  // @@protoc_insertion_point(class_scope:PublicTransportationService.StopArrivalTimeResponse)
  private static final com.example.PublicTransportationService.StopArrivalTimeResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.example.PublicTransportationService.StopArrivalTimeResponse();
  }

  public static com.example.PublicTransportationService.StopArrivalTimeResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<StopArrivalTimeResponse>
      PARSER = new com.google.protobuf.AbstractParser<StopArrivalTimeResponse>() {
    @java.lang.Override
    public StopArrivalTimeResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new StopArrivalTimeResponse(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<StopArrivalTimeResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<StopArrivalTimeResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.example.PublicTransportationService.StopArrivalTimeResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

