// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: PublicTransportationService.proto

package com.example.PublicTransportationService;

public interface StopArrivalTimeResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:PublicTransportationService.StopArrivalTimeResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string stop_id = 1;</code>
   */
  java.lang.String getStopId();
  /**
   * <code>string stop_id = 1;</code>
   */
  com.google.protobuf.ByteString
      getStopIdBytes();

  /**
   * <code>string current_location = 2;</code>
   */
  java.lang.String getCurrentLocation();
  /**
   * <code>string current_location = 2;</code>
   */
  com.google.protobuf.ByteString
      getCurrentLocationBytes();

  /**
   * <code>int32 estimated_minutes = 3;</code>
   */
  int getEstimatedMinutes();
}
