// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: PublicTransportationService.proto

package com.example.PublicTransportationService;

public final class TransitProto {
  private TransitProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_PublicTransportationService_GetRealTimeInfoRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_PublicTransportationService_GetRealTimeInfoRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_PublicTransportationService_StopArrivalTimeResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_PublicTransportationService_StopArrivalTimeResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_PublicTransportationService_DispatchVehicleRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_PublicTransportationService_DispatchVehicleRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_PublicTransportationService_DispatchVehicleResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_PublicTransportationService_DispatchVehicleResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n!PublicTransportationService.proto\022\033Pub" +
      "licTransportationService\",\n\026GetRealTimeI" +
      "nfoRequest\022\022\n\nvehicle_id\030\001 \001(\t\"_\n\027StopAr" +
      "rivalTimeResponse\022\017\n\007stop_id\030\001 \001(\t\022\030\n\020cu" +
      "rrent_location\030\002 \001(\t\022\031\n\021estimated_minute" +
      "s\030\003 \001(\005\"L\n\026DispatchVehicleRequest\022\024\n\014veh" +
      "icle_type\030\001 \001(\t\022\034\n\024destination_location\030" +
      "\002 \001(\t\"M\n\027DispatchVehicleResponse\022\022\n\nvehi" +
      "cle_id\030\001 \001(\t\022\036\n\026estimated_arrival_time\030\002" +
      " \001(\t2\250\002\n\033PublicTransportationService\022\205\001\n" +
      "\026GetRealTimeTransitInfo\0223.PublicTranspor" +
      "tationService.GetRealTimeInfoRequest\0324.P" +
      "ublicTransportationService.StopArrivalTi" +
      "meResponse\"\000\022\200\001\n\017DispatchVehicle\0223.Publi" +
      "cTransportationService.DispatchVehicleRe" +
      "quest\0324.PublicTransportationService.Disp" +
      "atchVehicleResponse\"\0000\001B9\n\'com.example.P" +
      "ublicTransportationServiceB\014TransitProto" +
      "P\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_PublicTransportationService_GetRealTimeInfoRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_PublicTransportationService_GetRealTimeInfoRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_PublicTransportationService_GetRealTimeInfoRequest_descriptor,
        new java.lang.String[] { "VehicleId", });
    internal_static_PublicTransportationService_StopArrivalTimeResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_PublicTransportationService_StopArrivalTimeResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_PublicTransportationService_StopArrivalTimeResponse_descriptor,
        new java.lang.String[] { "StopId", "CurrentLocation", "EstimatedMinutes", });
    internal_static_PublicTransportationService_DispatchVehicleRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_PublicTransportationService_DispatchVehicleRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_PublicTransportationService_DispatchVehicleRequest_descriptor,
        new java.lang.String[] { "VehicleType", "DestinationLocation", });
    internal_static_PublicTransportationService_DispatchVehicleResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_PublicTransportationService_DispatchVehicleResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_PublicTransportationService_DispatchVehicleResponse_descriptor,
        new java.lang.String[] { "VehicleId", "EstimatedArrivalTime", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
