// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ParkingService.proto

package com.example.ParkingService;

public interface ParkingLotResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ParkingService.ParkingLotResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 available_spaces = 1;</code>
   */
  int getAvailableSpaces();

  /**
   * <code>int32 total_spaces = 2;</code>
   */
  int getTotalSpaces();
}
