// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ParkingService.proto

package com.example.ParkingService;

public final class ParkingServiceProto {
  private ParkingServiceProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ParkingService_ParkingLotRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ParkingService_ParkingLotRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ParkingService_ParkingLotResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ParkingService_ParkingLotResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ParkingService_ParkingReservationRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ParkingService_ParkingReservationRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ParkingService_ParkingReservationResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ParkingService_ParkingReservationResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\024ParkingService.proto\022\016ParkingService\"+" +
      "\n\021ParkingLotRequest\022\026\n\016parking_lot_id\030\001 " +
      "\001(\t\"D\n\022ParkingLotResponse\022\030\n\020available_s" +
      "paces\030\001 \001(\005\022\024\n\014total_spaces\030\002 \001(\005\"^\n\031Par" +
      "kingReservationRequest\022\017\n\007user_id\030\001 \001(\t\022" +
      "\026\n\016parking_lot_id\030\002 \001(\t\022\030\n\020reservation_t" +
      "ime\030\003 \001(\t\"Q\n\032ParkingReservationResponse\022" +
      "\027\n\017confirmation_id\030\001 \001(\t\022\032\n\022reservation_" +
      "status\030\002 \001(\t2\346\001\n\016ParkingService\022d\n\031FindA" +
      "vailableParkingSpace\022!.ParkingService.Pa" +
      "rkingLotRequest\032\".ParkingService.Parking" +
      "LotResponse\"\000\022n\n\021BookParkingSpaces\022).Par" +
      "kingService.ParkingReservationRequest\032*." +
      "ParkingService.ParkingReservationRespons" +
      "e\"\000(\001B3\n\032com.example.ParkingServiceB\023Par" +
      "kingServiceProtoP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_ParkingService_ParkingLotRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_ParkingService_ParkingLotRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ParkingService_ParkingLotRequest_descriptor,
        new java.lang.String[] { "ParkingLotId", });
    internal_static_ParkingService_ParkingLotResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_ParkingService_ParkingLotResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ParkingService_ParkingLotResponse_descriptor,
        new java.lang.String[] { "AvailableSpaces", "TotalSpaces", });
    internal_static_ParkingService_ParkingReservationRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_ParkingService_ParkingReservationRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ParkingService_ParkingReservationRequest_descriptor,
        new java.lang.String[] { "UserId", "ParkingLotId", "ReservationTime", });
    internal_static_ParkingService_ParkingReservationResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_ParkingService_ParkingReservationResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ParkingService_ParkingReservationResponse_descriptor,
        new java.lang.String[] { "ConfirmationId", "ReservationStatus", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
