// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ParkingService.proto

package com.example.ParkingService;

/**
 * Protobuf type {@code ParkingService.ParkingLotResponse}
 */
public  final class ParkingLotResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:ParkingService.ParkingLotResponse)
    ParkingLotResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use ParkingLotResponse.newBuilder() to construct.
  private ParkingLotResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ParkingLotResponse() {
    availableSpaces_ = 0;
    totalSpaces_ = 0;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private ParkingLotResponse(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {

            availableSpaces_ = input.readInt32();
            break;
          }
          case 16: {

            totalSpaces_ = input.readInt32();
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.example.ParkingService.ParkingServiceProto.internal_static_ParkingService_ParkingLotResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.example.ParkingService.ParkingServiceProto.internal_static_ParkingService_ParkingLotResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.example.ParkingService.ParkingLotResponse.class, com.example.ParkingService.ParkingLotResponse.Builder.class);
  }

  public static final int AVAILABLE_SPACES_FIELD_NUMBER = 1;
  private int availableSpaces_;
  /**
   * <code>int32 available_spaces = 1;</code>
   */
  public int getAvailableSpaces() {
    return availableSpaces_;
  }

  public static final int TOTAL_SPACES_FIELD_NUMBER = 2;
  private int totalSpaces_;
  /**
   * <code>int32 total_spaces = 2;</code>
   */
  public int getTotalSpaces() {
    return totalSpaces_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (availableSpaces_ != 0) {
      output.writeInt32(1, availableSpaces_);
    }
    if (totalSpaces_ != 0) {
      output.writeInt32(2, totalSpaces_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (availableSpaces_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, availableSpaces_);
    }
    if (totalSpaces_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(2, totalSpaces_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.example.ParkingService.ParkingLotResponse)) {
      return super.equals(obj);
    }
    com.example.ParkingService.ParkingLotResponse other = (com.example.ParkingService.ParkingLotResponse) obj;

    boolean result = true;
    result = result && (getAvailableSpaces()
        == other.getAvailableSpaces());
    result = result && (getTotalSpaces()
        == other.getTotalSpaces());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + AVAILABLE_SPACES_FIELD_NUMBER;
    hash = (53 * hash) + getAvailableSpaces();
    hash = (37 * hash) + TOTAL_SPACES_FIELD_NUMBER;
    hash = (53 * hash) + getTotalSpaces();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.example.ParkingService.ParkingLotResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.example.ParkingService.ParkingLotResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.example.ParkingService.ParkingLotResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.example.ParkingService.ParkingLotResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.example.ParkingService.ParkingLotResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.example.ParkingService.ParkingLotResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.example.ParkingService.ParkingLotResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.example.ParkingService.ParkingLotResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.example.ParkingService.ParkingLotResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.example.ParkingService.ParkingLotResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.example.ParkingService.ParkingLotResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.example.ParkingService.ParkingLotResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.example.ParkingService.ParkingLotResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code ParkingService.ParkingLotResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:ParkingService.ParkingLotResponse)
      com.example.ParkingService.ParkingLotResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.example.ParkingService.ParkingServiceProto.internal_static_ParkingService_ParkingLotResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.example.ParkingService.ParkingServiceProto.internal_static_ParkingService_ParkingLotResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.example.ParkingService.ParkingLotResponse.class, com.example.ParkingService.ParkingLotResponse.Builder.class);
    }

    // Construct using com.example.ParkingService.ParkingLotResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      availableSpaces_ = 0;

      totalSpaces_ = 0;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.example.ParkingService.ParkingServiceProto.internal_static_ParkingService_ParkingLotResponse_descriptor;
    }

    @java.lang.Override
    public com.example.ParkingService.ParkingLotResponse getDefaultInstanceForType() {
      return com.example.ParkingService.ParkingLotResponse.getDefaultInstance();
    }

    @java.lang.Override
    public com.example.ParkingService.ParkingLotResponse build() {
      com.example.ParkingService.ParkingLotResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.example.ParkingService.ParkingLotResponse buildPartial() {
      com.example.ParkingService.ParkingLotResponse result = new com.example.ParkingService.ParkingLotResponse(this);
      result.availableSpaces_ = availableSpaces_;
      result.totalSpaces_ = totalSpaces_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.example.ParkingService.ParkingLotResponse) {
        return mergeFrom((com.example.ParkingService.ParkingLotResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.example.ParkingService.ParkingLotResponse other) {
      if (other == com.example.ParkingService.ParkingLotResponse.getDefaultInstance()) return this;
      if (other.getAvailableSpaces() != 0) {
        setAvailableSpaces(other.getAvailableSpaces());
      }
      if (other.getTotalSpaces() != 0) {
        setTotalSpaces(other.getTotalSpaces());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.example.ParkingService.ParkingLotResponse parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.example.ParkingService.ParkingLotResponse) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private int availableSpaces_ ;
    /**
     * <code>int32 available_spaces = 1;</code>
     */
    public int getAvailableSpaces() {
      return availableSpaces_;
    }
    /**
     * <code>int32 available_spaces = 1;</code>
     */
    public Builder setAvailableSpaces(int value) {
      
      availableSpaces_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 available_spaces = 1;</code>
     */
    public Builder clearAvailableSpaces() {
      
      availableSpaces_ = 0;
      onChanged();
      return this;
    }

    private int totalSpaces_ ;
    /**
     * <code>int32 total_spaces = 2;</code>
     */
    public int getTotalSpaces() {
      return totalSpaces_;
    }
    /**
     * <code>int32 total_spaces = 2;</code>
     */
    public Builder setTotalSpaces(int value) {
      
      totalSpaces_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 total_spaces = 2;</code>
     */
    public Builder clearTotalSpaces() {
      
      totalSpaces_ = 0;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:ParkingService.ParkingLotResponse)
  }

  // @@protoc_insertion_point(class_scope:ParkingService.ParkingLotResponse)
  private static final com.example.ParkingService.ParkingLotResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.example.ParkingService.ParkingLotResponse();
  }

  public static com.example.ParkingService.ParkingLotResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ParkingLotResponse>
      PARSER = new com.google.protobuf.AbstractParser<ParkingLotResponse>() {
    @java.lang.Override
    public ParkingLotResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new ParkingLotResponse(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<ParkingLotResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ParkingLotResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.example.ParkingService.ParkingLotResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

