// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ParkingService.proto

package com.example.ParkingService;

public interface ParkingReservationResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ParkingService.ParkingReservationResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string confirmation_id = 1;</code>
   */
  java.lang.String getConfirmationId();
  /**
   * <code>string confirmation_id = 1;</code>
   */
  com.google.protobuf.ByteString
      getConfirmationIdBytes();

  /**
   * <code>string reservation_status = 2;</code>
   */
  java.lang.String getReservationStatus();
  /**
   * <code>string reservation_status = 2;</code>
   */
  com.google.protobuf.ByteString
      getReservationStatusBytes();
}
