// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ParkingService.proto

package com.example.ParkingService;

public interface ParkingLotRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ParkingService.ParkingLotRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string parking_lot_id = 1;</code>
   */
  java.lang.String getParkingLotId();
  /**
   * <code>string parking_lot_id = 1;</code>
   */
  com.google.protobuf.ByteString
      getParkingLotIdBytes();
}
