// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ParkingService.proto

package com.example.ParkingService;

public interface ParkingReservationRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ParkingService.ParkingReservationRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string user_id = 1;</code>
   */
  java.lang.String getUserId();
  /**
   * <code>string user_id = 1;</code>
   */
  com.google.protobuf.ByteString
      getUserIdBytes();

  /**
   * <code>string parking_lot_id = 2;</code>
   */
  java.lang.String getParkingLotId();
  /**
   * <code>string parking_lot_id = 2;</code>
   */
  com.google.protobuf.ByteString
      getParkingLotIdBytes();

  /**
   * <code>string reservation_time = 3;</code>
   */
  java.lang.String getReservationTime();
  /**
   * <code>string reservation_time = 3;</code>
   */
  com.google.protobuf.ByteString
      getReservationTimeBytes();
}
