// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: BikeSharingService.proto

package com.example.BikeSharingService;

public final class BikeSharingServiceProto {
  private BikeSharingServiceProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_BikeSharingService_CheckBikeAvailabilityRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_BikeSharingService_CheckBikeAvailabilityRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_BikeSharingService_CheckBikeAvailabilityResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_BikeSharingService_CheckBikeAvailabilityResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_BikeSharingService_ReserveAndUnlockBikeRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_BikeSharingService_ReserveAndUnlockBikeRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_BikeSharingService_ReserveAndUnlockBikeResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_BikeSharingService_ReserveAndUnlockBikeResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\030BikeSharingService.proto\022\022BikeSharingS" +
      "ervice\"2\n\034CheckBikeAvailabilityRequest\022\022" +
      "\n\nstation_id\030\001 \001(\t\"8\n\035CheckBikeAvailabil" +
      "ityResponse\022\027\n\017available_bikes\030\001 \001(\005\"\\\n\033" +
      "ReserveAndUnlockBikeRequest\022\017\n\007user_id\030\001" +
      " \001(\t\022\022\n\nstation_id\030\002 \001(\t\022\030\n\020reservation_" +
      "time\030\003 \001(\t\"\224\001\n\034ReserveAndUnlockBikeRespo" +
      "nse\022\026\n\016reservation_id\030\001 \001(\t\022\023\n\013status_co" +
      "de\030\002 \001(\005\022\017\n\007bike_id\030\003 \001(\t\022\036\n\026unlock_expi" +
      "ration_time\030\004 \001(\t\022\026\n\016update_message\030\005 \001(" +
      "\t2\225\002\n\022BikeSharingService\022~\n\025CheckBikeAva" +
      "ilability\0220.BikeSharingService.CheckBike" +
      "AvailabilityRequest\0321.BikeSharingService" +
      ".CheckBikeAvailabilityResponse\"\000\022\177\n\024Rese" +
      "rveAndUnlockBike\022/.BikeSharingService.Re" +
      "serveAndUnlockBikeRequest\0320.BikeSharingS" +
      "ervice.ReserveAndUnlockBikeResponse\"\000(\0010" +
      "\001B;\n\036com.example.BikeSharingServiceB\027Bik" +
      "eSharingServiceProtoP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_BikeSharingService_CheckBikeAvailabilityRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_BikeSharingService_CheckBikeAvailabilityRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_BikeSharingService_CheckBikeAvailabilityRequest_descriptor,
        new java.lang.String[] { "StationId", });
    internal_static_BikeSharingService_CheckBikeAvailabilityResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_BikeSharingService_CheckBikeAvailabilityResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_BikeSharingService_CheckBikeAvailabilityResponse_descriptor,
        new java.lang.String[] { "AvailableBikes", });
    internal_static_BikeSharingService_ReserveAndUnlockBikeRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_BikeSharingService_ReserveAndUnlockBikeRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_BikeSharingService_ReserveAndUnlockBikeRequest_descriptor,
        new java.lang.String[] { "UserId", "StationId", "ReservationTime", });
    internal_static_BikeSharingService_ReserveAndUnlockBikeResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_BikeSharingService_ReserveAndUnlockBikeResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_BikeSharingService_ReserveAndUnlockBikeResponse_descriptor,
        new java.lang.String[] { "ReservationId", "StatusCode", "BikeId", "UnlockExpirationTime", "UpdateMessage", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
