// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: BikeSharingService.proto

package com.example.BikeSharingService;

public interface CheckBikeAvailabilityResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:BikeSharingService.CheckBikeAvailabilityResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * The number of available bikes at the station
   * </pre>
   *
   * <code>int32 available_bikes = 1;</code>
   */
  int getAvailableBikes();
}
