// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: BikeSharingService.proto

package com.example.BikeSharingService;

public interface CheckBikeAvailabilityRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:BikeSharingService.CheckBikeAvailabilityRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * The ID of the bike station
   * </pre>
   *
   * <code>string station_id = 1;</code>
   */
  java.lang.String getStationId();
  /**
   * <pre>
   * The ID of the bike station
   * </pre>
   *
   * <code>string station_id = 1;</code>
   */
  com.google.protobuf.ByteString
      getStationIdBytes();
}
