// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: BikeSharingService.proto

package com.example.BikeSharingService;

/**
 * <pre>
 *Unary RPC 
 * </pre>
 *
 * Protobuf type {@code BikeSharingService.CheckBikeAvailabilityRequest}
 */
public  final class CheckBikeAvailabilityRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:BikeSharingService.CheckBikeAvailabilityRequest)
    CheckBikeAvailabilityRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use CheckBikeAvailabilityRequest.newBuilder() to construct.
  private CheckBikeAvailabilityRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private CheckBikeAvailabilityRequest() {
    stationId_ = "";
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private CheckBikeAvailabilityRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            stationId_ = s;
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.example.BikeSharingService.BikeSharingServiceProto.internal_static_BikeSharingService_CheckBikeAvailabilityRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.example.BikeSharingService.BikeSharingServiceProto.internal_static_BikeSharingService_CheckBikeAvailabilityRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.example.BikeSharingService.CheckBikeAvailabilityRequest.class, com.example.BikeSharingService.CheckBikeAvailabilityRequest.Builder.class);
  }

  public static final int STATION_ID_FIELD_NUMBER = 1;
  private volatile java.lang.Object stationId_;
  /**
   * <pre>
   * The ID of the bike station
   * </pre>
   *
   * <code>string station_id = 1;</code>
   */
  public java.lang.String getStationId() {
    java.lang.Object ref = stationId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      stationId_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * The ID of the bike station
   * </pre>
   *
   * <code>string station_id = 1;</code>
   */
  public com.google.protobuf.ByteString
      getStationIdBytes() {
    java.lang.Object ref = stationId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      stationId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getStationIdBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, stationId_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getStationIdBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, stationId_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.example.BikeSharingService.CheckBikeAvailabilityRequest)) {
      return super.equals(obj);
    }
    com.example.BikeSharingService.CheckBikeAvailabilityRequest other = (com.example.BikeSharingService.CheckBikeAvailabilityRequest) obj;

    boolean result = true;
    result = result && getStationId()
        .equals(other.getStationId());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + STATION_ID_FIELD_NUMBER;
    hash = (53 * hash) + getStationId().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.example.BikeSharingService.CheckBikeAvailabilityRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.example.BikeSharingService.CheckBikeAvailabilityRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.example.BikeSharingService.CheckBikeAvailabilityRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.example.BikeSharingService.CheckBikeAvailabilityRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.example.BikeSharingService.CheckBikeAvailabilityRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.example.BikeSharingService.CheckBikeAvailabilityRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.example.BikeSharingService.CheckBikeAvailabilityRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.example.BikeSharingService.CheckBikeAvailabilityRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.example.BikeSharingService.CheckBikeAvailabilityRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.example.BikeSharingService.CheckBikeAvailabilityRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.example.BikeSharingService.CheckBikeAvailabilityRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.example.BikeSharingService.CheckBikeAvailabilityRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.example.BikeSharingService.CheckBikeAvailabilityRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   *Unary RPC 
   * </pre>
   *
   * Protobuf type {@code BikeSharingService.CheckBikeAvailabilityRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:BikeSharingService.CheckBikeAvailabilityRequest)
      com.example.BikeSharingService.CheckBikeAvailabilityRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.example.BikeSharingService.BikeSharingServiceProto.internal_static_BikeSharingService_CheckBikeAvailabilityRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.example.BikeSharingService.BikeSharingServiceProto.internal_static_BikeSharingService_CheckBikeAvailabilityRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.example.BikeSharingService.CheckBikeAvailabilityRequest.class, com.example.BikeSharingService.CheckBikeAvailabilityRequest.Builder.class);
    }

    // Construct using com.example.BikeSharingService.CheckBikeAvailabilityRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      stationId_ = "";

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.example.BikeSharingService.BikeSharingServiceProto.internal_static_BikeSharingService_CheckBikeAvailabilityRequest_descriptor;
    }

    @java.lang.Override
    public com.example.BikeSharingService.CheckBikeAvailabilityRequest getDefaultInstanceForType() {
      return com.example.BikeSharingService.CheckBikeAvailabilityRequest.getDefaultInstance();
    }

    @java.lang.Override
    public com.example.BikeSharingService.CheckBikeAvailabilityRequest build() {
      com.example.BikeSharingService.CheckBikeAvailabilityRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.example.BikeSharingService.CheckBikeAvailabilityRequest buildPartial() {
      com.example.BikeSharingService.CheckBikeAvailabilityRequest result = new com.example.BikeSharingService.CheckBikeAvailabilityRequest(this);
      result.stationId_ = stationId_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.example.BikeSharingService.CheckBikeAvailabilityRequest) {
        return mergeFrom((com.example.BikeSharingService.CheckBikeAvailabilityRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.example.BikeSharingService.CheckBikeAvailabilityRequest other) {
      if (other == com.example.BikeSharingService.CheckBikeAvailabilityRequest.getDefaultInstance()) return this;
      if (!other.getStationId().isEmpty()) {
        stationId_ = other.stationId_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.example.BikeSharingService.CheckBikeAvailabilityRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.example.BikeSharingService.CheckBikeAvailabilityRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object stationId_ = "";
    /**
     * <pre>
     * The ID of the bike station
     * </pre>
     *
     * <code>string station_id = 1;</code>
     */
    public java.lang.String getStationId() {
      java.lang.Object ref = stationId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        stationId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * The ID of the bike station
     * </pre>
     *
     * <code>string station_id = 1;</code>
     */
    public com.google.protobuf.ByteString
        getStationIdBytes() {
      java.lang.Object ref = stationId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        stationId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * The ID of the bike station
     * </pre>
     *
     * <code>string station_id = 1;</code>
     */
    public Builder setStationId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      stationId_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The ID of the bike station
     * </pre>
     *
     * <code>string station_id = 1;</code>
     */
    public Builder clearStationId() {
      
      stationId_ = getDefaultInstance().getStationId();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The ID of the bike station
     * </pre>
     *
     * <code>string station_id = 1;</code>
     */
    public Builder setStationIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      stationId_ = value;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:BikeSharingService.CheckBikeAvailabilityRequest)
  }

  // @@protoc_insertion_point(class_scope:BikeSharingService.CheckBikeAvailabilityRequest)
  private static final com.example.BikeSharingService.CheckBikeAvailabilityRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.example.BikeSharingService.CheckBikeAvailabilityRequest();
  }

  public static com.example.BikeSharingService.CheckBikeAvailabilityRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<CheckBikeAvailabilityRequest>
      PARSER = new com.google.protobuf.AbstractParser<CheckBikeAvailabilityRequest>() {
    @java.lang.Override
    public CheckBikeAvailabilityRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new CheckBikeAvailabilityRequest(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<CheckBikeAvailabilityRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<CheckBikeAvailabilityRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.example.BikeSharingService.CheckBikeAvailabilityRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

