// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: BikeSharingService.proto

package com.example.BikeSharingService;

/**
 * Protobuf type {@code BikeSharingService.ReserveAndUnlockBikeResponse}
 */
public  final class ReserveAndUnlockBikeResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:BikeSharingService.ReserveAndUnlockBikeResponse)
    ReserveAndUnlockBikeResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use ReserveAndUnlockBikeResponse.newBuilder() to construct.
  private ReserveAndUnlockBikeResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ReserveAndUnlockBikeResponse() {
    reservationId_ = "";
    statusCode_ = 0;
    bikeId_ = "";
    unlockExpirationTime_ = "";
    updateMessage_ = "";
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private ReserveAndUnlockBikeResponse(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            reservationId_ = s;
            break;
          }
          case 16: {

            statusCode_ = input.readInt32();
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();

            bikeId_ = s;
            break;
          }
          case 34: {
            java.lang.String s = input.readStringRequireUtf8();

            unlockExpirationTime_ = s;
            break;
          }
          case 42: {
            java.lang.String s = input.readStringRequireUtf8();

            updateMessage_ = s;
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.example.BikeSharingService.BikeSharingServiceProto.internal_static_BikeSharingService_ReserveAndUnlockBikeResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.example.BikeSharingService.BikeSharingServiceProto.internal_static_BikeSharingService_ReserveAndUnlockBikeResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.example.BikeSharingService.ReserveAndUnlockBikeResponse.class, com.example.BikeSharingService.ReserveAndUnlockBikeResponse.Builder.class);
  }

  public static final int RESERVATION_ID_FIELD_NUMBER = 1;
  private volatile java.lang.Object reservationId_;
  /**
   * <code>string reservation_id = 1;</code>
   */
  public java.lang.String getReservationId() {
    java.lang.Object ref = reservationId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      reservationId_ = s;
      return s;
    }
  }
  /**
   * <code>string reservation_id = 1;</code>
   */
  public com.google.protobuf.ByteString
      getReservationIdBytes() {
    java.lang.Object ref = reservationId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      reservationId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int STATUS_CODE_FIELD_NUMBER = 2;
  private int statusCode_;
  /**
   * <pre>
   * Status code indicating success or failure of the reservation
   * </pre>
   *
   * <code>int32 status_code = 2;</code>
   */
  public int getStatusCode() {
    return statusCode_;
  }

  public static final int BIKE_ID_FIELD_NUMBER = 3;
  private volatile java.lang.Object bikeId_;
  /**
   * <pre>
   * The ID of the bike to unlock
   * </pre>
   *
   * <code>string bike_id = 3;</code>
   */
  public java.lang.String getBikeId() {
    java.lang.Object ref = bikeId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      bikeId_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * The ID of the bike to unlock
   * </pre>
   *
   * <code>string bike_id = 3;</code>
   */
  public com.google.protobuf.ByteString
      getBikeIdBytes() {
    java.lang.Object ref = bikeId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      bikeId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int UNLOCK_EXPIRATION_TIME_FIELD_NUMBER = 4;
  private volatile java.lang.Object unlockExpirationTime_;
  /**
   * <pre>
   * The time until which the bike can be unlocked
   * </pre>
   *
   * <code>string unlock_expiration_time = 4;</code>
   */
  public java.lang.String getUnlockExpirationTime() {
    java.lang.Object ref = unlockExpirationTime_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      unlockExpirationTime_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * The time until which the bike can be unlocked
   * </pre>
   *
   * <code>string unlock_expiration_time = 4;</code>
   */
  public com.google.protobuf.ByteString
      getUnlockExpirationTimeBytes() {
    java.lang.Object ref = unlockExpirationTime_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      unlockExpirationTime_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int UPDATE_MESSAGE_FIELD_NUMBER = 5;
  private volatile java.lang.Object updateMessage_;
  /**
   * <pre>
   * A message providing status updates
   * </pre>
   *
   * <code>string update_message = 5;</code>
   */
  public java.lang.String getUpdateMessage() {
    java.lang.Object ref = updateMessage_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      updateMessage_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * A message providing status updates
   * </pre>
   *
   * <code>string update_message = 5;</code>
   */
  public com.google.protobuf.ByteString
      getUpdateMessageBytes() {
    java.lang.Object ref = updateMessage_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      updateMessage_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getReservationIdBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, reservationId_);
    }
    if (statusCode_ != 0) {
      output.writeInt32(2, statusCode_);
    }
    if (!getBikeIdBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, bikeId_);
    }
    if (!getUnlockExpirationTimeBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, unlockExpirationTime_);
    }
    if (!getUpdateMessageBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 5, updateMessage_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getReservationIdBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, reservationId_);
    }
    if (statusCode_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(2, statusCode_);
    }
    if (!getBikeIdBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, bikeId_);
    }
    if (!getUnlockExpirationTimeBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, unlockExpirationTime_);
    }
    if (!getUpdateMessageBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, updateMessage_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.example.BikeSharingService.ReserveAndUnlockBikeResponse)) {
      return super.equals(obj);
    }
    com.example.BikeSharingService.ReserveAndUnlockBikeResponse other = (com.example.BikeSharingService.ReserveAndUnlockBikeResponse) obj;

    boolean result = true;
    result = result && getReservationId()
        .equals(other.getReservationId());
    result = result && (getStatusCode()
        == other.getStatusCode());
    result = result && getBikeId()
        .equals(other.getBikeId());
    result = result && getUnlockExpirationTime()
        .equals(other.getUnlockExpirationTime());
    result = result && getUpdateMessage()
        .equals(other.getUpdateMessage());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + RESERVATION_ID_FIELD_NUMBER;
    hash = (53 * hash) + getReservationId().hashCode();
    hash = (37 * hash) + STATUS_CODE_FIELD_NUMBER;
    hash = (53 * hash) + getStatusCode();
    hash = (37 * hash) + BIKE_ID_FIELD_NUMBER;
    hash = (53 * hash) + getBikeId().hashCode();
    hash = (37 * hash) + UNLOCK_EXPIRATION_TIME_FIELD_NUMBER;
    hash = (53 * hash) + getUnlockExpirationTime().hashCode();
    hash = (37 * hash) + UPDATE_MESSAGE_FIELD_NUMBER;
    hash = (53 * hash) + getUpdateMessage().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.example.BikeSharingService.ReserveAndUnlockBikeResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.example.BikeSharingService.ReserveAndUnlockBikeResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.example.BikeSharingService.ReserveAndUnlockBikeResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.example.BikeSharingService.ReserveAndUnlockBikeResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.example.BikeSharingService.ReserveAndUnlockBikeResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.example.BikeSharingService.ReserveAndUnlockBikeResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.example.BikeSharingService.ReserveAndUnlockBikeResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.example.BikeSharingService.ReserveAndUnlockBikeResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.example.BikeSharingService.ReserveAndUnlockBikeResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.example.BikeSharingService.ReserveAndUnlockBikeResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.example.BikeSharingService.ReserveAndUnlockBikeResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.example.BikeSharingService.ReserveAndUnlockBikeResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.example.BikeSharingService.ReserveAndUnlockBikeResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code BikeSharingService.ReserveAndUnlockBikeResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:BikeSharingService.ReserveAndUnlockBikeResponse)
      com.example.BikeSharingService.ReserveAndUnlockBikeResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.example.BikeSharingService.BikeSharingServiceProto.internal_static_BikeSharingService_ReserveAndUnlockBikeResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.example.BikeSharingService.BikeSharingServiceProto.internal_static_BikeSharingService_ReserveAndUnlockBikeResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.example.BikeSharingService.ReserveAndUnlockBikeResponse.class, com.example.BikeSharingService.ReserveAndUnlockBikeResponse.Builder.class);
    }

    // Construct using com.example.BikeSharingService.ReserveAndUnlockBikeResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      reservationId_ = "";

      statusCode_ = 0;

      bikeId_ = "";

      unlockExpirationTime_ = "";

      updateMessage_ = "";

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.example.BikeSharingService.BikeSharingServiceProto.internal_static_BikeSharingService_ReserveAndUnlockBikeResponse_descriptor;
    }

    @java.lang.Override
    public com.example.BikeSharingService.ReserveAndUnlockBikeResponse getDefaultInstanceForType() {
      return com.example.BikeSharingService.ReserveAndUnlockBikeResponse.getDefaultInstance();
    }

    @java.lang.Override
    public com.example.BikeSharingService.ReserveAndUnlockBikeResponse build() {
      com.example.BikeSharingService.ReserveAndUnlockBikeResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.example.BikeSharingService.ReserveAndUnlockBikeResponse buildPartial() {
      com.example.BikeSharingService.ReserveAndUnlockBikeResponse result = new com.example.BikeSharingService.ReserveAndUnlockBikeResponse(this);
      result.reservationId_ = reservationId_;
      result.statusCode_ = statusCode_;
      result.bikeId_ = bikeId_;
      result.unlockExpirationTime_ = unlockExpirationTime_;
      result.updateMessage_ = updateMessage_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.example.BikeSharingService.ReserveAndUnlockBikeResponse) {
        return mergeFrom((com.example.BikeSharingService.ReserveAndUnlockBikeResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.example.BikeSharingService.ReserveAndUnlockBikeResponse other) {
      if (other == com.example.BikeSharingService.ReserveAndUnlockBikeResponse.getDefaultInstance()) return this;
      if (!other.getReservationId().isEmpty()) {
        reservationId_ = other.reservationId_;
        onChanged();
      }
      if (other.getStatusCode() != 0) {
        setStatusCode(other.getStatusCode());
      }
      if (!other.getBikeId().isEmpty()) {
        bikeId_ = other.bikeId_;
        onChanged();
      }
      if (!other.getUnlockExpirationTime().isEmpty()) {
        unlockExpirationTime_ = other.unlockExpirationTime_;
        onChanged();
      }
      if (!other.getUpdateMessage().isEmpty()) {
        updateMessage_ = other.updateMessage_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.example.BikeSharingService.ReserveAndUnlockBikeResponse parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.example.BikeSharingService.ReserveAndUnlockBikeResponse) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object reservationId_ = "";
    /**
     * <code>string reservation_id = 1;</code>
     */
    public java.lang.String getReservationId() {
      java.lang.Object ref = reservationId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        reservationId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string reservation_id = 1;</code>
     */
    public com.google.protobuf.ByteString
        getReservationIdBytes() {
      java.lang.Object ref = reservationId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        reservationId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string reservation_id = 1;</code>
     */
    public Builder setReservationId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      reservationId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string reservation_id = 1;</code>
     */
    public Builder clearReservationId() {
      
      reservationId_ = getDefaultInstance().getReservationId();
      onChanged();
      return this;
    }
    /**
     * <code>string reservation_id = 1;</code>
     */
    public Builder setReservationIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      reservationId_ = value;
      onChanged();
      return this;
    }

    private int statusCode_ ;
    /**
     * <pre>
     * Status code indicating success or failure of the reservation
     * </pre>
     *
     * <code>int32 status_code = 2;</code>
     */
    public int getStatusCode() {
      return statusCode_;
    }
    /**
     * <pre>
     * Status code indicating success or failure of the reservation
     * </pre>
     *
     * <code>int32 status_code = 2;</code>
     */
    public Builder setStatusCode(int value) {
      
      statusCode_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Status code indicating success or failure of the reservation
     * </pre>
     *
     * <code>int32 status_code = 2;</code>
     */
    public Builder clearStatusCode() {
      
      statusCode_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object bikeId_ = "";
    /**
     * <pre>
     * The ID of the bike to unlock
     * </pre>
     *
     * <code>string bike_id = 3;</code>
     */
    public java.lang.String getBikeId() {
      java.lang.Object ref = bikeId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        bikeId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * The ID of the bike to unlock
     * </pre>
     *
     * <code>string bike_id = 3;</code>
     */
    public com.google.protobuf.ByteString
        getBikeIdBytes() {
      java.lang.Object ref = bikeId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        bikeId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * The ID of the bike to unlock
     * </pre>
     *
     * <code>string bike_id = 3;</code>
     */
    public Builder setBikeId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      bikeId_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The ID of the bike to unlock
     * </pre>
     *
     * <code>string bike_id = 3;</code>
     */
    public Builder clearBikeId() {
      
      bikeId_ = getDefaultInstance().getBikeId();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The ID of the bike to unlock
     * </pre>
     *
     * <code>string bike_id = 3;</code>
     */
    public Builder setBikeIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      bikeId_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object unlockExpirationTime_ = "";
    /**
     * <pre>
     * The time until which the bike can be unlocked
     * </pre>
     *
     * <code>string unlock_expiration_time = 4;</code>
     */
    public java.lang.String getUnlockExpirationTime() {
      java.lang.Object ref = unlockExpirationTime_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        unlockExpirationTime_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * The time until which the bike can be unlocked
     * </pre>
     *
     * <code>string unlock_expiration_time = 4;</code>
     */
    public com.google.protobuf.ByteString
        getUnlockExpirationTimeBytes() {
      java.lang.Object ref = unlockExpirationTime_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        unlockExpirationTime_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * The time until which the bike can be unlocked
     * </pre>
     *
     * <code>string unlock_expiration_time = 4;</code>
     */
    public Builder setUnlockExpirationTime(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      unlockExpirationTime_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The time until which the bike can be unlocked
     * </pre>
     *
     * <code>string unlock_expiration_time = 4;</code>
     */
    public Builder clearUnlockExpirationTime() {
      
      unlockExpirationTime_ = getDefaultInstance().getUnlockExpirationTime();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The time until which the bike can be unlocked
     * </pre>
     *
     * <code>string unlock_expiration_time = 4;</code>
     */
    public Builder setUnlockExpirationTimeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      unlockExpirationTime_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object updateMessage_ = "";
    /**
     * <pre>
     * A message providing status updates
     * </pre>
     *
     * <code>string update_message = 5;</code>
     */
    public java.lang.String getUpdateMessage() {
      java.lang.Object ref = updateMessage_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        updateMessage_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * A message providing status updates
     * </pre>
     *
     * <code>string update_message = 5;</code>
     */
    public com.google.protobuf.ByteString
        getUpdateMessageBytes() {
      java.lang.Object ref = updateMessage_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        updateMessage_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * A message providing status updates
     * </pre>
     *
     * <code>string update_message = 5;</code>
     */
    public Builder setUpdateMessage(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      updateMessage_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * A message providing status updates
     * </pre>
     *
     * <code>string update_message = 5;</code>
     */
    public Builder clearUpdateMessage() {
      
      updateMessage_ = getDefaultInstance().getUpdateMessage();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * A message providing status updates
     * </pre>
     *
     * <code>string update_message = 5;</code>
     */
    public Builder setUpdateMessageBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      updateMessage_ = value;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:BikeSharingService.ReserveAndUnlockBikeResponse)
  }

  // @@protoc_insertion_point(class_scope:BikeSharingService.ReserveAndUnlockBikeResponse)
  private static final com.example.BikeSharingService.ReserveAndUnlockBikeResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.example.BikeSharingService.ReserveAndUnlockBikeResponse();
  }

  public static com.example.BikeSharingService.ReserveAndUnlockBikeResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ReserveAndUnlockBikeResponse>
      PARSER = new com.google.protobuf.AbstractParser<ReserveAndUnlockBikeResponse>() {
    @java.lang.Override
    public ReserveAndUnlockBikeResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new ReserveAndUnlockBikeResponse(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<ReserveAndUnlockBikeResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ReserveAndUnlockBikeResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.example.BikeSharingService.ReserveAndUnlockBikeResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

