// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: BikeSharingService.proto

package com.example.BikeSharingService;

public interface ReserveAndUnlockBikeRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:BikeSharingService.ReserveAndUnlockBikeRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string user_id = 1;</code>
   */
  java.lang.String getUserId();
  /**
   * <code>string user_id = 1;</code>
   */
  com.google.protobuf.ByteString
      getUserIdBytes();

  /**
   * <code>string station_id = 2;</code>
   */
  java.lang.String getStationId();
  /**
   * <code>string station_id = 2;</code>
   */
  com.google.protobuf.ByteString
      getStationIdBytes();

  /**
   * <code>string reservation_time = 3;</code>
   */
  java.lang.String getReservationTime();
  /**
   * <code>string reservation_time = 3;</code>
   */
  com.google.protobuf.ByteString
      getReservationTimeBytes();
}
